### ISSUE TITLE
Also add style for other input elements

### ISSUE THREAD

**Issue by CodeBrauer** [KingPixil/wing#8] opened 2016-06-30 13:22 UTC
Currently there is only `[type="text"]` and `[type="button"]` styled. But there are so many more: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes

So I've already tried some tweaks, but there is no perfect solution without having a selector that contains all this types (or at least the most common)

Like this (messy & not classy 😅):

``` css
input:not([type=submit]):not([type=radio]):not([type=checkbox]):not([type=reset]), select
/* or this */
input[type=text], input[type=password], input[type=email], input[type=number], input[type=search], input[type=url], input[type=tel], input[type=datetime], input[type=color], input[type=date]
```

in [forms.css#L6](https://github.com/KingPixil/wing/blob/master/src/forms.css#L6)

So the other point is, this framework should cover this (or at least some of the most common types) in my opinion - but it would make also the filesize bigger.

![screenshot-wing-html](https://cloud.githubusercontent.com/assets/2059754/16489287/1fe43732-3ed5-11e6-8e4a-0b4fa137323b.png)
[gist of the screenshot](https://gist.github.com/CodeBrauer/38d41258d215ea13b6d3103f6df77725)

**Comment by KingPixil** [comment] 2016-06-30 16:00
Yes, I have been thinking about this as well, the problem is that it will add more file size, so the first step is to fix up #10. Which will reduce the file size, then I can start adding more inputs.

What input's should be added? 

All I think is critical:
- Radio
- Checkbox

If you have any other ones, please let me know.

Thanks. :+1:

**Comment by ShaggyDude** [comment] 2016-07-19 18:59
The file size is already tiny but, this could be added as a module to be included if desired? Also, you need to add height to select to make it the same height as text input...  Awesome stuff!

**Comment by KingPixil** [comment] 2016-07-19 19:01
@ShaggyDude Thanks for the feedback, I guess I could add it as a module, but I am working on it being included with Wing so stay tuned!

Also, what browser are you seeing the select input on? It already has height on Chrome, on Macs there are some problems however...

Thanks!

**Comment by KingPixil** [comment] 2016-07-20 19:05
@CodeBrauer @ShaggyDude I added support for input type text, password, email, and a couple other **common** ones, I will be adding support for radio and checkbox soon.

**Comment by Kcchouette** [comment] 2016-10-06 09:57
@KingPixil Can you please also add support for `input file`, `input url` and `input tel`?

**Comment by KingPixil** [comment] 2016-10-06 14:23
I'll work on it @Kcchouette 👍

**Comment by KingPixil** [comment] 2017-03-16 01:37
Added it @Kcchouette, it will be in v1

**Closed by KingPixil** 2017-03-16 01:37 UTC
Labels: enhancement, Priority: Medium
